src/main/java/net/java/cargotracker/interfaces/booking/facade/dto/CargoRoute.java
package net.java.cargotracker.interfaces.booking.facade.dto;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import net.java.cargotracker.application.util.DateUtil;
import net.java.cargotracker.application.util.LocationUtil;

/**
 * DTO for registering and routing a cargo.
 */
public class CargoRoute implements Serializable {

    private static final long serialVersionUID = 1L;
    private static final SimpleDateFormat DATE_FORMAT
            = new SimpleDateFormat("MM/dd/yyyy hh:mm a z");

    private final String trackingId;
    private final String origin;
    private final String finalDestination;
    private final String arrivalDeadline;
    private final boolean misrouted;
    private final List<Leg> legs;
    private final boolean claimed;
    private final String lastKnownLocation;
    private final String transportStatus;
    private String nextLocation;

    public CargoRoute(String trackingId, String origin, String finalDestination,
            Date arrivalDeadline, boolean misrouted, boolean claimed, String lastKnownLocation, String transportStatus) {
        this.trackingId = trackingId;
        this.origin = origin;
        this.finalDestination = finalDestination;
        this.arrivalDeadline = DATE_FORMAT.format(arrivalDeadline);
        this.misrouted = misrouted;
        this.claimed = claimed;
        this.lastKnownLocation = lastKnownLocation;
        this.transportStatus = transportStatus;
        this.legs = new ArrayList<>();
    }

    public String getTrackingId() {
        return trackingId;
    }

    public String getOrigin() {
        return origin;
    }
    
    public String getOriginName() {
        return LocationUtil.getLocationName(origin);
    }

    public String getOriginCode() {
        return LocationUtil.getLocationCode(origin);
    }

    public String getFinalDestination() {
        return finalDestination;
    }
    
    public String getFinalDestinationName() {
        return LocationUtil.getLocationName(finalDestination);
    }
    
    public String getFinalDestinationCode() {
        return LocationUtil.getLocationCode(finalDestination);
    }

    public void addLeg(
            String voyageNumber,
            String fromUnLocode, String fromName,
            String toUnLocode, String toName,
            Date loadTime, Date unloadTime) {
        legs.add(new Leg(voyageNumber,
                fromUnLocode, fromName,
                toUnLocode, toName,
                loadTime, unloadTime));
    }

    public List<Leg> getLegs() {
        return Collections.unmodifiableList(legs);
    }

    public boolean isMisrouted() {
        return misrouted;
    }

    public boolean isRouted() {
        return !legs.isEmpty();
    }

    public String getArrivalDeadline() {
        return arrivalDeadline;
    }
    
    public String getArrivalDeadlineDate() {
        return DateUtil.getDateFromDateTime(arrivalDeadline); 
    }

    public String getArrivalDeadlineTime() {
        return DateUtil.getTimeFromDateTime(arrivalDeadline);
    }

    public boolean isClaimed() {
        return claimed;
    }

    public String getLastKnownLocation() {
        return this.lastKnownLocation;
    }
    
    public String getLastKnownLocationName() {
        return LocationUtil.getLocationName(lastKnownLocation);
    }
    
    public String getLastKnownLocationCode() {
        return LocationUtil.getLocationCode(lastKnownLocation);
    }

    public String getTransportStatus() {
        return this.transportStatus;
    }

    public String getNextLocation() {
        return this.nextLocation;
    }
}

src/main/java/net/java/cargotracker/interfaces/booking/facade/dto/Leg.java
package net.java.cargotracker.interfaces.booking.facade.dto;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import net.java.cargotracker.application.util.DateUtil;

/**
 * DTO for a leg in an itinerary.
 */
public class Leg implements Serializable {

    private static final SimpleDateFormat DATE_FORMAT
            = new SimpleDateFormat("MM/dd/yyyy hh:mm a z");

    private final String voyageNumber;
    private final String fromUnLocode;
    private final String fromName;
    private final String toUnLocode;
    private final String toName;
    private final String loadTime;
    private final String unloadTime;

    public Leg(
            String voyageNumber,
            String fromUnLocode,
            String fromName,
            String toUnLocode,
            String toName,
            Date loadTime,
            Date unloadTime) {
        this.voyageNumber = voyageNumber;
        this.fromUnLocode = fromUnLocode;
        this.fromName = fromName;
        this.toUnLocode = toUnLocode;
        this.toName = toName;
        this.loadTime = DATE_FORMAT.format(loadTime);
        this.unloadTime = DATE_FORMAT.format(unloadTime);
    }

    public String getVoyageNumber() {
        return voyageNumber;
    }

    public String getFrom() {
        return fromName + " (" + fromUnLocode + ")";
    }

    public String getFromUnLocode() {
        return fromUnLocode;
    }

    public String getFromName() {
        return fromName;
    }

    public String getTo() {
        return toUnLocode + " (" + toName + ")";
    }

    public String getToName() {
        return toName;
    }

    public String getToUnLocode() {
        return toUnLocode;
    }

    public String getLoadTime() {
        return loadTime;
    }

    public String getLoadTimeDate() {
        return DateUtil.getDateFromDateTime(loadTime);
    }

    public String getLoadTimeTime() {
        return DateUtil.getTimeFromDateTime(loadTime);
    }

    public String getUnloadTime() {
        return unloadTime;
    }

    public String getUnloadTimeTime() {
        return DateUtil.getTimeFromDateTime(unloadTime);
    }

    public String getUnloadTimeDate() {
        return DateUtil.getDateFromDateTime(unloadTime);
    }

    @Override
    public String toString() {
        return "Leg{" + "voyageNumber=" + voyageNumber + ", from=" + fromUnLocode + ", to=" + toUnLocode + ", loadTime=" + loadTime + ", unloadTime=" + unloadTime + '}';
    }
}

src/main/java/net/java/cargotracker/interfaces/booking/facade/dto/Location.java
package net.java.cargotracker.interfaces.booking.facade.dto;

import java.io.Serializable;

/**
 * Location DTO.
 */
public class Location implements Serializable {

    private static final long serialVersionUID = 1L;
    private String unLocode;
    private String name;

    public Location(String unLocode, String name) {
        this.unLocode = unLocode;
        this.name = name;
    }

    public String getUnLocode() {
        return unLocode;
    }

    public String getName() {
        return name + " (" + unLocode + ")";
    }

    public String getNameOnly() {
        return name;
    }
}

src/main/java/net/java/cargotracker/interfaces/booking/facade/dto/RouteCandidate.java
package net.java.cargotracker.interfaces.booking.facade.dto;

import java.io.Serializable;
import java.util.Collections;
import java.util.List;

/**
 * DTO for presenting and selecting an itinerary from a collection of
 * candidates.
 */
public class RouteCandidate implements Serializable {

    private List<Leg> legs;

    public RouteCandidate(List<Leg> legs) {
        this.legs = legs;
    }

    public List<Leg> getLegs() {
        return Collections.unmodifiableList(legs);
    }

    @Override
    public String toString() {
        return "RouteCandidate{" + "legs=" + legs + '}';
    }
}

src/main/webapp/booking/booking-date.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <ui:composition template="/WEB-INF/templates/common/admin.xhtml">

        <ui:define name="title">Cargo Registration</ui:define>
        <h:head>
            <style>
                <!-- work around to fix selectonemenu bug in Chrome & Safari -->
                .ui-selectonemenu-label{
                    width:90% !important;
                }
            </style>
        </h:head>

        <ui:define name="content">

            <div class="ui-grid ui-grid-responsive">
                <div class="ui-grid-row">
                    <div class="ui-grid-col-3" id="leftCol"></div>
                    <div class="ui-grid-col-6" id="mainCol">

                        <br/>
                        <h:form id="dateForm">
                            <p:outputLabel value="3. Set the arrival deadline for this new #{bookingBackingBean.originName}-#{bookingBackingBean.destinationName} cargo " />
                            <hr/>

                            <h:panelGrid columns="2" styleClass="registrationPanelGrid" style="margin: 0 auto;">
                                <p:calendar id="deadline" value="#{bookingBackingBean.arrivalDeadline}" mindate="#{bookingBackingBean.today}" mode="inline" pattern="yyyy-MM-dd">
                                    <p:ajax event="dateSelect" listener="#{bookingBackingBean.deadlineUpdated}"/>
                                </p:calendar>
                            </h:panelGrid>

                            <h:panelGrid columns="2" id="durationPanel" styleClass="registrationPanelGrid" style="margin: 0 auto;" >
                                <p:outputLabel value="A journey can't start and end the same day!" rendered="#{bookingBackingBean.duration eq 0}"/>
                                <p:outputLabel value="Journey duration is one day." rendered="#{bookingBackingBean.duration eq 1}"/>
                                <p:outputLabel value="Journey duration is #{bookingBackingBean.duration} days." rendered="#{bookingBackingBean.duration gt 1}"/>
                            </h:panelGrid>

                            <hr/>   

                            <h:panelGrid columns="5" styleClass="registrationPanelGrid" style="margin: 0 auto;">
                                <p:commandButton value="Back" action="booking-destination" />
                                <p:commandButton value="Cancel" action="/admin/dashboard" />
                                <p:commandButton value="Book Cargo" id="bookBtn" action="#{bookingBackingBean.register()}" disabled="#{!bookingBackingBean.bookable}"/>
                            </h:panelGrid>

                        </h:form>
                    </div>

                    <div class="ui-grid-col-3" id="leftCol"></div>
                </div>
            </div>

        </ui:define>
    </ui:composition>
</html>

src/main/webapp/booking/booking-destination.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    
    <ui:composition template="/WEB-INF/templates/common/admin.xhtml">
        <ui:define name="title">Cargo Registration</ui:define>        
        <h:head>
            <style>
                <!-- work around to fix selectonemenu bug in Chrome & Safari -->
                .ui-selectonemenu-label{
                    width:90% !important;
                }
            </style>
        </h:head>
        
        
        <ui:define name="content">

            <div class="ui-grid ui-grid-responsive">
                <div class="ui-grid-row">
                    <div class="ui-grid-col-3" id="leftCol"></div>
                    <div class="ui-grid-col-6" id="mainCol">

                        <br/>
                        <h:form>
                            <p:outputLabel value="2. Set the destination for this new cargo coming from #{bookingBackingBean.originName}" />
                            <hr/>
                            <p:selectOneMenu id="destination" value="#{bookingBackingBean.destinationUnlocode}">
                                <f:selectItems value="#{bookingBackingBean.locations}" var="location"
                                               itemLabel="#{location.name} " itemValue="#{location.unLocode}" />
                            </p:selectOneMenu>
                            <hr/>   

                            <h:panelGrid columns="5" styleClass="registrationPanelGrid" style="margin: 0 auto;">
                                <p:commandButton value="Back" action="booking" />
                                <p:commandButton value="Cancel" action="/admin/dashboard" />
                                <p:commandButton value="Next" action="booking-date" />

                            </h:panelGrid>

                        </h:form>
                    </div>

                    <div class="ui-grid-col-3" id="leftCol"></div>
                </div>
            </div>
    
    
        </ui:define>
        
        
    </ui:composition>
        
        
</html>

src/main/webapp/booking/booking.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <ui:composition template="/WEB-INF/templates/common/admin.xhtml">
        <ui:define name="title">Cargo Registration</ui:define>        
        <h:head>
            <style>
                <!-- work around to fix selectonemenu bug in Chrome & Safari -->
                .ui-selectonemenu-label{
                    width:90% !important;
                }
            </style>
        </h:head>
       
        
        <ui:define name="content">

            <div class="ui-grid ui-grid-responsive">
                <div class="ui-grid-row">
                    <div class="ui-grid-col-3" id="leftCol"></div>
                    <div class="ui-grid-col-6" id="mainCol">

                        <br/>
                        <h:form>
                            <p:outputLabel value="1.Choose the origin of the new cargo" />
                            <hr/>
                                <p:selectOneMenu id="origin" value="#{bookingBackingBean.originUnlocode}">
                                    <f:selectItems value="#{bookingBackingBean.locations}" var="location"
                                                   itemLabel="#{location.name}" itemValue="#{location.unLocode}" />
                                </p:selectOneMenu>                            
                            <hr/>

                            <h:panelGrid columns="2" style="margin: 0 auto;">
                                <p:commandButton value="Cancel" action="/admin/dashboard" /><p:commandButton value="Next" action="booking-destination" />                        
                            </h:panelGrid>
                        
                        </h:form>

                    </div>
                    <div class="ui-grid-col-3" id="leftCol"></div>
                </div>
            </div>

        </ui:define>
    </ui:composition>
</html>